baseurl = "http://eduk8s-hub.io/"
languageCode = "en-us"
title = "eduk8s Hub - Kubernetes workshops/labs"
paginate = 12

[params]
  img = "eduk8s.png"
  defaultImage = "eduk8s.png"
  twitter = "http://twitter.com/eduk8sio"
  github = "http://github.com/eduk8s"
  analytics = ""

  [params.copyright]
    name = "eduk8s"
    link = "https://eduk8s.io"

[menu]

  [[menu.main]]
#    identifier = "Install"
    name = "Install"
    pre = "<i class='fa fa-bolt'></i>"
    url = "/pages/install/"
    weight = -200

  [[menu.main]]
    name = "Read the docs"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "https://eduk8s.readthedocs.io/"
    weight = -100

  [[menu.main]]
    name = "About"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-bookmark'></i>"
    url = "/pages/about/"
    weight = -90

  [[menu.main]]
    name = "Contact"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-user-circle'></i>"
    url = "/pages/contact/"
    weight = -80
